// ═══ Postio Coach: client-ready report export ═══
// Dependency-free: builds a clean, branded HTML document and opens it in a new
// window for the browser's native "Save as PDF". Falls back to downloading the
// .html file if the popup is blocked. No new packages.

import type { PostAnalysis, StrategyData } from '@engine/lib/model/types';
import type { StringKey } from '@engine/lib/i18n/strings';

type T = (key: StringKey, vars?: Record<string, string | number>) => string;

const esc = (s: string) => s.replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c] as string));
const ddmmyyyy = () => { const d = new Date(); const p = (n: number) => String(n).padStart(2, '0'); return `${p(d.getDate())}.${p(d.getMonth() + 1)}.${d.getFullYear()}`; };

function shell(title: string, brandName: string, body: string): string {
  return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title>
<style>
  :root { --v:#6d28d9; --ink:#18181b; --muted:#71717a; --line:#e4e4e7; }
  * { box-sizing:border-box; }
  body { font-family:-apple-system,Segoe UI,Roboto,Inter,sans-serif; color:var(--ink); margin:0; padding:40px; line-height:1.5; }
  .head { display:flex; justify-content:space-between; align-items:baseline; border-bottom:2px solid var(--v); padding-bottom:12px; margin-bottom:24px; }
  .brand { font-size:20px; font-weight:800; letter-spacing:-0.01em; }
  .meta { color:var(--muted); font-size:12px; }
  h1 { font-size:24px; margin:0 0 4px; letter-spacing:-0.01em; }
  h2 { font-size:14px; text-transform:uppercase; letter-spacing:0.04em; color:var(--muted); margin:24px 0 8px; }
  h3 { font-size:15px; margin:16px 0 4px; }
  ul { margin:6px 0; padding-left:18px; } li { margin:3px 0; font-size:13px; }
  p { font-size:13px; }
  .score { font-size:40px; font-weight:800; color:var(--v); }
  .card { border:1px solid var(--line); border-radius:12px; padding:14px; margin:8px 0; }
  .grid { display:grid; grid-template-columns:1fr 1fr; gap:10px; }
  .chip { display:inline-block; background:#f4f4f5; border-radius:6px; padding:2px 8px; font-size:11px; margin:2px 4px 2px 0; }
  table { width:100%; border-collapse:collapse; font-size:12px; }
  td,th { border-bottom:1px solid var(--line); padding:6px 8px; text-align:left; vertical-align:top; }
  .foot { margin-top:28px; border-top:1px solid var(--line); padding-top:10px; color:var(--muted); font-size:11px; }
  @media print { body { padding:0; } @page { margin:18mm; } }
</style></head><body>
<div class="head"><span class="brand">${esc(brandName)}</span><span class="meta">${esc(title)} · ${ddmmyyyy()}</span></div>
${body}
<div class="foot">Generated by Postio Coach. Advice is guidance, not a guarantee.</div>
<script>window.onload=function(){setTimeout(function(){window.print();},300);};</script>
</body></html>`;
}

function open(html: string, filename: string): void {
  const w = window.open('', '_blank');
  if (w && w.document) { w.document.open(); w.document.write(html); w.document.close(); return; }
  // popup blocked -> download the html
  const blob = new Blob([html], { type: 'text/html' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(a.href), 2000);
}

export function exportAnalysisReport(t: T, brandName: string, postName: string, a: PostAnalysis | Omit<PostAnalysis, 'id' | 'createdAt'>): void {
  const li = (xs: string[]) => xs.map((x) => `<li>${esc(x)}</li>`).join('');
  const cats = [...a.benchmarkResults].sort((x, y) => x.score - y.score).map((r) =>
    `<tr><td><b>${esc(r.label)}</b><br><span style="color:#71717a">${esc(r.summary)}</span>${r.issue ? `<br><span style="color:#b45309">${esc(r.issue)}</span>` : ''}<br>${esc(r.recommendation)}</td><td style="text-align:right;font-weight:700">${r.score}</td></tr>`).join('');
  const body = `
    <h1>${esc(postName)}</h1>
    <p class="meta">${esc(t('coach.overallScore'))}</p>
    <div class="score">${a.overallScore}</div>
    ${a.platformNotes ? `<p>${esc(a.platformNotes)}</p>` : ''}
    <div class="grid">
      <div class="card"><h3>${esc(t('coach.topStrengths'))}</h3><ul>${li(a.strengths)}</ul></div>
      <div class="card"><h3>${esc(t('coach.topIssues'))}</h3><ul>${li(a.issues)}</ul></div>
    </div>
    <h2>${esc(t('coach.actionPlan'))}</h2>
    <div class="grid">
      <div class="card"><h3>${esc(t('coach.plan.quickWins'))}</h3><ul>${li(a.actionPlan.quickWins)}</ul></div>
      <div class="card"><h3>${esc(t('coach.plan.recommendedEdits'))}</h3><ul>${li(a.actionPlan.recommendedEdits)}</ul></div>
      <div class="card"><h3>${esc(t('coach.plan.experimentalIdeas'))}</h3><ul>${li(a.actionPlan.experimentalIdeas)}</ul></div>
      <div class="card"><h3>${esc(t('coach.plan.risks'))}</h3><ul>${li(a.actionPlan.risks)}</ul></div>
    </div>
    <h2>${esc(t('coach.benchmarkScores'))}</h2>
    <table><tbody>${cats}</tbody></table>`;
  open(shell(t('coach.report.analysisTitle'), brandName, body), 'postio-coach-analysis.html');
}

export function exportStrategyReport(t: T, brandName: string, playLabel: string, data: StrategyData): void {
  let body = `<h1>${esc(playLabel)}</h1>`;
  if (data.kind === 'sections') {
    if (data.summary) body += `<p>${esc(data.summary)}</p>`;
    body += data.sections.map((s) => `<div class="card"><h3>${esc(s.heading)}</h3>${s.body ? `<p>${esc(s.body)}</p>` : ''}<ul>${(s.bullets ?? []).map((b) => `<li>${esc(b)}</li>`).join('')}</ul></div>`).join('');
  } else if (data.kind === 'pillars') {
    if (data.summary) body += `<p>${esc(data.summary)}</p>`;
    body += data.pillars.map((p, i) => `<div class="card"><h3>${i + 1}. ${esc(p.name)}</h3><p style="color:#71717a">${esc(p.why)}</p>${p.topics.map((x) => `<span class="chip">${esc(x)}</span>`).join('')}</div>`).join('');
  } else if (data.kind === 'calendar') {
    if (data.summary) body += `<p>${esc(data.summary)}</p>`;
    body += `<table><thead><tr><th>#</th><th>${esc(t('coach.strategy.topics'))}</th><th>Format</th><th>${esc(t('coach.strategy.cta'))}</th></tr></thead><tbody>${data.days.map((d) => `<tr><td>${d.day}</td><td><b>${esc(d.idea)}</b><br><span style="color:#71717a">${esc(d.angle)}</span></td><td>${esc(d.format)}</td><td>${esc(d.goal)}</td></tr>`).join('')}</tbody></table>`;
  } else {
    body += `<div class="card"><h3>${esc(t('coach.strategy.hook'))}</h3><p>${esc(data.hook)}</p></div>`;
    body += `<div class="card"><h3>${esc(t('coach.strategy.insight'))}</h3><p>${esc(data.insight)}</p></div>`;
    body += `<div class="card"><h3>${esc(t('coach.strategy.cta'))}</h3><p>${esc(data.cta)}</p></div>`;
    if (data.caption) body += `<div class="card"><h3>${esc(t('coach.strategy.caption'))}</h3><p>${esc(data.caption)}</p></div>`;
    if (data.hashtags?.length) body += `<p style="color:var(--v)">${esc(data.hashtags.join(' '))}</p>`;
  }
  open(shell(t('coach.report.strategyTitle'), brandName, body), 'postio-coach-strategy.html');
}
